// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Modelo.Dominio.Entidades
{
    public partial interface IDbContextoProcedures
    {
    }
}
