// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Modelo.Dominio.Entidades
{
    public partial class LogTransacoes : EntidadeBase
    {
        
        public Guid EntidadeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Data { get; set; }
        public Guid? UsuarioId { get; set; }
        [Column(TypeName = "ntext")]
        public string Dados { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Comando { get; set; }

        public string EntidadeNome { get; set; }

        [ForeignKey("UsuarioId")]
        [InverseProperty("LogTransacoes")]
        public virtual Usuarios Usuario { get; set; }
    }
}