// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Modelo.Dominio.Entidades
{
    public partial class Perfis : EntidadeBase
    {
        public Perfis()
        {
            PermissoesPerfis = new HashSet<PermissoesPerfis>();
            Usuarios = new HashSet<Usuarios>();
        }

        [Required]
        [StringLength(256)]
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool? Administrador { get; set; }
        
        [InverseProperty("Perfil")]
        public virtual ICollection<PermissoesPerfis> PermissoesPerfis { get; set; }
        [InverseProperty("Perfil")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}