// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Modelo.Dominio.Entidades
{
    public partial class PermissoesPerfis :EntidadeBase
    {
       
        public Guid PerfilId { get; set; }
        public Guid TipoAcessoId { get; set; }
        public int TipoAcaoId { get; set; }
        

        [ForeignKey("PerfilId")]
        [InverseProperty("PermissoesPerfis")]
        public virtual Perfis Perfil { get; set; }
        [ForeignKey("TipoAcaoId")]
        [InverseProperty("PermissoesPerfis")]
        public virtual TipoAcao TipoAcao { get; set; }
        [ForeignKey("TipoAcessoId")]
        [InverseProperty("PermissoesPerfis")]
        public virtual TipoAcesso TipoAcesso { get; set; }
    }
}