// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace Modelo.Dominio.Entidades;

public partial class ResetarSenha : EntidadeBase
{   
    public String Token { get; set; }

    public Guid UsuarioId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataSolicitacao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataExpiracao { get; set; }

    public bool? Efetivado { get; set; }
   
    [ForeignKey("UsuarioId")]
    [InverseProperty("ResetarSenha")]
    public virtual Usuarios IdUsuarioNavigation { get; set; }
}