// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Modelo.Dominio.Entidades
{
    public partial class TipoAcao
    {
        public TipoAcao()
        {
            PermissoesPerfis = new HashSet<PermissoesPerfis>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Acao { get; set; }
        public bool Excluido { get; set; }

        [InverseProperty("TipoAcao")]
        public virtual ICollection<PermissoesPerfis> PermissoesPerfis { get; set; }
    }
}