// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Modelo.Dominio.Entidades
{
    public partial class TipoAcesso
    {
        public TipoAcesso()
        {
            PermissoesPerfis = new HashSet<PermissoesPerfis>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Tipo { get; set; }
        public bool Excluido { get; set; }

        [InverseProperty("TipoAcesso")]
        public virtual ICollection<PermissoesPerfis> PermissoesPerfis { get; set; }
    }
}